import {createClient} from '@sanity/client'

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET
const apiVersion = process.env.NEXT_PUBLIC_SANITY_API_VERSION || '2025-09-25'
const token = process.env.SANITY_API_WRITE_TOKEN

if (!projectId || !dataset) {
  throw new Error(
    'Missing NEXT_PUBLIC_SANITY_PROJECT_ID or NEXT_PUBLIC_SANITY_DATASET environment variables',
  )
}
if (!token) {
  throw new Error(
    'Missing SANITY_API_WRITE_TOKEN environment variable (needs write access) to run the seed script',
  )
}

const client = createClient({projectId, dataset, apiVersion, token, useCdn: false})

function slugify(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

function block(text) {
  return [
    {
      _type: 'block',
      _key: 'seed-block-1',
      style: 'normal',
      children: [{_type: 'span', _key: 'seed-span-1', text}],
      markDefs: [],
    },
  ]
}

const categories = [
  {id: 'postCategory.engineering', title: 'Engineering', description: 'Deep dives into how we build things.'},
  {id: 'postCategory.design', title: 'Design', description: 'Notes on craft, process, and visual design.'},
  {id: 'postCategory.product', title: 'Product', description: 'Product decisions and roadmap thinking.'},
  {
    id: 'postCategory.company-news',
    title: 'Company News',
    description: 'Announcements and updates from the team.',
  },
  {id: 'postCategory.tutorials', title: 'Tutorials', description: 'Step-by-step guides.'},
]

const postTitles = [
  'Shipping our new component library',
  'How we redesigned the onboarding flow',
  'A field guide to GROQ queries',
  'What we learned migrating to the App Router',
  'Behind the scenes: our design system tokens',
  'Announcing our Series B',
  'Building accessible forms from scratch',
  'Why we chose Sanity for content modeling',
  'Five patterns for scalable Next.js apps',
  'Our new brand identity, explained',
  'Debugging performance regressions in production',
  'Welcoming three new engineers to the team',
  'A tutorial on Portable Text customization',
  'Rethinking our release process',
  'Design critique: what makes a good empty state',
]

async function seedCategories() {
  for (const category of categories) {
    await client.createIfNotExists({
      _id: category.id,
      _type: 'postCategory',
      title: category.title,
      slug: {_type: 'slug', current: slugify(category.title)},
      description: category.description,
    })
  }
  console.log(`Seeded ${categories.length} categories`)
}

async function seedPosts() {
  for (let i = 0; i < postTitles.length; i++) {
    const title = postTitles[i]
    const slug = slugify(title)
    const daysAgo = i * 4
    const date = new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000).toISOString()
    const assignedCategoryIds = [
      categories[i % categories.length].id,
      categories[(i + 2) % categories.length].id,
    ]

    await client.createIfNotExists({
      _id: `post.seed-${i + 1}`,
      _type: 'post',
      title,
      slug: {_type: 'slug', current: slug},
      excerpt: `A sample excerpt for "${title}", generated by the seed script.`,
      content: block(
        `This is placeholder body content for "${title}". Replace with real writing in Sanity Studio.`,
      ),
      date,
      categories: assignedCategoryIds.map((id) => ({
        _type: 'reference',
        _ref: id,
        _key: id,
      })),
    })
  }
  console.log(`Seeded ${postTitles.length} posts`)
}

async function seedPostSettings() {
  await client.createIfNotExists({
    _id: 'postSettings',
    _type: 'postSettings',
    postsPerPage: 6,
    loadMoreMode: 'button',
  })
  console.log('Seeded post settings (postsPerPage: 6, loadMoreMode: button)')
}

async function run() {
  await seedCategories()
  await seedPosts()
  await seedPostSettings()
}

run().catch((err) => {
  console.error(err)
  process.exit(1)
})
